app:
  version: 1.0.0
logging:
  level:
    org.springframework.web: DEBUG

server.port: 8087

spring:

#Multipartfile
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

#Kafka
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      group-id: halco
    listener:
      ack-mode: RECORD

  datasource:

    driver-class-name: org.postgresql.Driver
    platform: postgres

    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: false
    driverClassName: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

cloudinary-api-key: ${CLOUDINARY_API_KEY}
cloudinary-secret-key: ${CLOUDINARY_SECRET_KEY}
cloudinary-name: ${CLOUDINARY_NAME}
jwt-secret-key: ${jwt-secret-key}